#!/bin/bash 
#引数チェック
if [ "$#" -lt 2 ]; then
	echo 'Invalid argument'
	exit 22
fi

#数値チェック関数
int_chk()
{
expr "$1" + 1 >/dev/null 2>&1
if [ "$?" -ne 0 ] || [ "$1" -lt 1 ]; then
	echo 'Invalid argument'
	exit 22
fi
} 

#数値チェック
for arg in "$@"
do 
	int_chk "${arg}"
done

#ユークリッドの互除法関数
Euclid()
{
# a > b
if [ "$1" -gt "$2" ]; then
	a="$1"
	b="$2"
elif [ "$1" -lt "$2" ]; then
	a="$2"
	b="$1"
else
	return "$1"
fi

c=$[$a-$b]

if [ "$b" -eq "$c" ]; then
	return "$c"
else
	Euclid "$b" "$c"
fi
}

#最大公約数を求める
n=0
for i in "$@"
do
	if [ "$n" -eq 0 ]; then x="${i}"
	else y="${i}"
	fi	

	if [ "$n" -ne 0 ]; then
		Euclid "$x" "$y"
		x="$c"
	else n=1
	fi
done

#最小公倍数を求める
ans=1
for i in "$@"
do
	ans=$[$ans*${i}]
done
ans=$[$ans/$c]
echo "$ans" 
